# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('location', geoposition.fields.GeopositionField(max_length=42)),
            ],
        ),
    ]
