# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 11:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productions', '0002_auto_20170706_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsupply',
            options={'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='testsupply',
            name='quantity',
            field=models.FloatField(default=0.0, verbose_name='Quantity in litres'),
        ),
        migrations.AddField(
            model_name='testsupply',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
