# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0003_auto_20170706_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsupply',
            options={},
        ),
    ]
