# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0004_auto_20170706_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsupply',
            name='user',
        ),
    ]
