# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0005_remove_testsupply_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsupply',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='testsupply',
            name='received_by',
        ),
    ]
