# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0006_auto_20170707_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsupply',
            old_name='from_user',
            new_name='received_by',
        ),
    ]
