# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 09:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productions', '0008_auto_20170707_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsupply',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='testsupply',
            name='supplied_by',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='user',
        ),
        migrations.AddField(
            model_name='supply',
            name='supplied_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supply',
            name='received_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TestSupply',
        ),
    ]
